{"uuid": "4a60d7e5-0276-4c40-a390-24f691b7bb5b", "children": ["9bbb825a-6681-44b4-9aaa-be14c6d28f98"], "befores": [{"name": "browser_management", "status": "passed", "start": 1752685836473, "stop": 1752685838475}], "afters": [{"name": "browser_management::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59269): Max retries exceeded with url: /session/94e97799e125329f558cf44c1e7b7b38/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108067a40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/tests/conftest.py\", line 77, in browser_management\n    attach.add_screenshot(browser)\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/utils/attach.py\", line 11, in add_screenshot\n    png = browser.driver.get_screenshot_as_png()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 1030, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 1040, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 451, in execute\n    response = cast(RemoteConnection, self.command_executor).execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/urllib3/_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 871, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/18.08 Page_Object/.venv/lib/python3.12/site-packages/urllib3/util/retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1752685850370, "stop": 1752685850372}], "start": 1752685836473, "stop": 1752685850372}